유저 귓속말차단기능추가
MineFactory-Resource/UtilTool pull request #16
Opened 2022-08-22 10:52 UTC by Fade-Jung

/귓속말차단 [플레이어] - [플레이어]의 귓속말을 차단합니다. 
/귓속말차단해제 [플레이어] - [플레이어]의 귓속말차단을 해제합니다.

======================[테스트 환경]========================
1. 마인크래프트 버전 : 1.18.2
2. 버킷의 종류 : purpur-1.18.2-1632
3. 해당 테스트서버에서의 설치되어 있던 플러그인 : F5ArmorStand, UtilTool
======================[테스트]========================
1. Uni_Fade 유저가 Choco1010에게 /귓속말차단 Choco1010을 통해서 귓속말차단을 함.
1의 결과 : Choco1010은 Uni_Fade에게 귓속말을 보낼때, "[UtilTool] Uni_Fade 님이 귓속말을 차단했습니다!" 문구가 출력됨.
                또한, Uni_Fade는 Choco1010가 보낸 귓속말을 볼 수 없음.
2. Choco1010 유저가 Uni_Fade에게 /귓속말차단 Uni_Fade를 통해서 귓속말 차단을 함.
2의 결과 : 1의 결과랑 동일. [각각의 대상자만 서로 변경]

3. Uni_Fade 유저가 기존에 귓속말 차단이 되어있었던 Choco1010에게 /귓속말차단해제 Choco1010을 통해서 차단을 해제함
3의 결과 : Choco1010이 Uni_Fade에게 정상적으로 귓속말을 보낼 수 있게 되었으며,
                Uni_Fade 유저가 이 귓속말을 수신함
                
4. Choco1010 유저가 기존에 귓속말 차단이 되어있었던 Uni_Fade에게 /귓속말차단해제 Uni_Fade 를 통해서 차단을 해제함
4의 결과 : 3의 결과랑 동일. [각각의 대상자만 서로 변경]

5. 서버가 리로드 되거나, 정상적으로 리붓이 됐을때 차단과 관련된 값이 저장이 되는가?
5의 결과 : ignoreplayer.yml 에 저장이 됨. [ ex : <차단을하는 유저의닉네임>.<차단 당한 유저의 닉네임> , Uni_Fade.Choco1010 ]

2022-08-22 10:56 UTC, LesserJang commented on src/main/java/net/teamuni/playerjoinandleave/IgnorePlayerManager.java
> +        file = new File(Bukkit.getServer().getPluginManager().getPlugin("UtilTool").getDataFolder(), "ignoreplayer.yml");
`main.getDataFolder` 사용하십셔

2022-08-22 11:06 UTC, Fade-Jung commented on src/main/java/net/teamuni/playerjoinandleave/IgnorePlayerManager.java
> +        file = new File(Bukkit.getServer().getPluginManager().getPlugin("UtilTool").getDataFolder(), "ignoreplayer.yml");
IgnorePlayerManager 포함, 이 방식과 동일한 방법을 쓰는 PlayerUuidManager , CommandsManager 클래스들도 수정을 완료했음을 알립니다

2022-08-22 11:47 UTC, LesserJang commented on src/main/java/net/teamuni/playerjoinandleave/UtilTool.java
> +            String targetIgnore = target.getName() + "." + player.getName();
args[0]이 null이거나 target이 null이면 NPE 에러가 뜨지 않을까요?

2022-08-22 11:48 UTC, Fade-Jung commented on src/main/java/net/teamuni/playerjoinandleave/UtilTool.java
> +            String targetIgnore = target.getName() + "." + player.getName();
if 조건문을 args[0] != null 로수정해보겠습니다.

2022-08-22 11:56 UTC, kari0707 requested changes

2022-08-22 11:56 UTC, kari0707 commented on src/main/java/net/teamuni/playerjoinandleave/UtilTool.java
> +        }
args[0]이 null 아니고, args[0]의 닉네임을 가진 플레이어가 존재하지 않을 때 NPE가 발생합니다.
이와 같은 형식이 한 곳 더 존재하니 두 곳 모두 수정 바랍니다

2022-08-22 13:46 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/playerjoinandleave/UtilTool.java
> +        if (cmd.getName().equalsIgnoreCase("귓속말차단") && player.hasPermission("utiltool.whisperignore")) {
/귓속말차단 명령어에서 "차단"은 TabComplete를 지원하면 어떨까요? 명령어가 /귓속말 차단 이렇게 될 수 있도록 하면 유저들이 /귓속말 명령어를 입력하면서 '이러한 기능도 있구나'라고 알 수 있을 거 같아요

2022-08-22 13:46 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/playerjoinandleave/UtilTool.java
> +        if (cmd.getName().equalsIgnoreCase("귓속말차단해제") && player.hasPermission("utiltool.whisperunignore")) {
이 부분도 TabComplete를 이용하면 좋을 것 같아요
/귓속말 차단 해제 <닉네임>

2022-08-22 13:46 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/playerjoinandleave/UtilTool.java
> +                        player.sendMessage("§e[UtilTool] " + target.getName() + " 님을 차단 한 것을 해제했습니다!");
메시지에 띄어쓰기 오타가 있어용

2022-08-22 13:46 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/playerjoinandleave/UtilTool.java
> +                        player.sendMessage("§c[UtilTool] " + target.getName() + " 님이 귓속말을 차단했습니다!");
유저들 입장에서 'UtilTool이 뭐지?'라는 생각을 할 수 있을 거 같아서 [UtilTool]은 모두 [알림]으로 바꾸는 것이 좋을 것 같아요. 
[알림] 색코드는 노란색으로 하면 좋을 것 같습니다 왜냐하면 서버 내에서 출력되는 [알림]은 모두 노란색으로 통일되어 있어용

2022-08-22 13:46 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/playerjoinandleave/UtilTool.java
> +                        player.sendMessage("§c[UtilTool] 차단 당하지 않은 플레이어 입니다!");
메시지에 띄어쓰기 오타가 있어용

2022-08-22 13:46 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/playerjoinandleave/UtilTool.java
> +                        player.sendMessage("§c[UtilTool] 이미 차단한 플레이어 입니다!");
메시지에 띄어쓰기 오타가 있어용

2022-08-22 13:46 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/playerjoinandleave/UtilTool.java
>                  player.sendMessage("§a[UtilTool] §f확성기 재사용 까지 §a" + BroadCasterCooldown.getCooldown(player) + "§f초 남았습니다");
메시지에 띄어쓰기 오타가 있어용

2022-08-23 09:37 UTC, Fade-Jung commented on src/main/java/net/teamuni/playerjoinandleave/UtilTool.java
> +        if (cmd.getName().equalsIgnoreCase("귓속말차단") && player.hasPermission("utiltool.whisperignore")) {
좋은생각 같습니다 기존의 /귓속말차단, /귓속말차단해제 의 명령어가 길었었는데
귓속말에다가 종속 시켜보겠습니다.

2022-08-23 11:30 UTC, Fade-Jung commented on src/main/java/net/teamuni/playerjoinandleave/UtilTool.java
> +        }
null 체크로 NPE 문제 해결했습니다

2022-08-28 07:36 UTC, Fade-Jung commented
기존 명령어
/귓속말차단 [플레이어] - [플레이어]의 귓속말을 차단합니다.
/귓속말차단해제 [플레이어] - [플레이어]의 귓속말차단을 해제합니다.
======================================================
                           변경 후 명령어
/차단 [플레이어] - [플레이어]의 귓속말을 차단합니다.
/차단해제 [플레이어] - [플레이어]의 귓속말차단을 해제합니다.
======================[테스트 환경]========================

마인크래프트 버전 : 1.18.2

버킷의 종류 : purpur-1.18.2-1632

해당 테스트서버에서의 설치되어 있던 플러그인 : UtilTool

2022-08-28 08:47 UTC, kari0707 approved these changes

2022-08-28 08:50 UTC, Seokhun-Yang approved these changes

2022-08-28 08:51 UTC, LesserJang approved these changes

2022-08-28 09:04 UTC, merged