게임모드 명령어 단축명령어 만들기
MineFactory-Resource/UtilTool pull request #19
Opened 2022-08-29 14:16 UTC by Fade-Jung

/gm 0 - 서바이벌 모드로 변경합니다. 
/gm 1 - 크리에이티브 모드로 변경합니다.
/gm 2 - 모험 모드로 변경합니다.
/gm 3 - 관전자 모드로 변경합니다.

/gmc - 크리에이티브 모드로 변경합니다.
/gms - 서바이벌 모드로 변경합니다.

====================================

2022-08-29 14:44 UTC, Seokhun-Yang requested changes

2022-08-29 14:44 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/playerjoinandleave/UtilTool.java
> +                        return false;
return false가 아닌 break로 수정하여 주세요

2022-08-29 14:44 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/playerjoinandleave/UtilTool.java
> +                        player.sendMessage("§6/gm 3 - 게임모드를 관전자 모드로 변경합니다.");
default에 break가 빠져있네요

2022-08-29 14:44 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/playerjoinandleave/UtilTool.java
> +        if (cmd.getName().equalsIgnoreCase("gm") && player.hasPermission("utiltool.gamemode")) {
/gm 까지 입력했을 때 0 1 2 3 이 suggest 되나요?
/gamemode 까지 입력하면 adventure, creative, spectator, survival 이 suggest 되듯이요

2022-08-29 15:23 UTC, Seokhun-Yang approved these changes

2022-08-30 09:50 UTC, LesserJang approved these changes

2022-08-30 10:50 UTC, merged