reload 명령어 /utiltool reload로 수정
MineFactory-Resource/UtilTool pull request #8
Opened 2022-05-16 07:19 UTC by Seokhun-Yang

2022-05-20 19:24 UTC, abelbeak commented
1일 혹은 6시간 간격으로 리마인드해주세요 @LesserJang @kari0707 @Seokhun-Yang

2022-05-20 19:29 UTC, abelbeak requested changes

2022-05-20 19:29 UTC, abelbeak commented on src/main/java/net/teamuni/playerjoinandleave/UtilTool.java
> +                Bukkit.getPluginManager().enablePlugin(this);
플러그인을 비활성화 시켰다가 활성화 시키는 이유가 있나요?
어떠한 목적인가요?

2022-05-20 19:29 UTC, abelbeak commented on src/main/java/net/teamuni/playerjoinandleave/UtilTool.java
> +                CommandsManager.save();
저장하는 구문을 무엇 때문에 필요한가요?
리로드 명령을 실행시켰을 때, 예상되는 시나리오와, 데이터의 바뀜이 어떻게 되나요?

2022-05-20 19:29 UTC, abelbeak commented on src/main/java/net/teamuni/playerjoinandleave/UtilTool.java
> +                player.sendMessage(ChatColor.GREEN + "" + ChatColor.BOLD + "UtilTool has been reloaded!");
Green, Bold 를 주는 값 사이에 "" 가 들어가야만 예상대로 동작하나요?
@kari0707 @LesserJang @Seokhun-Yang @Fade-Jung

2022-05-20 19:29 UTC, abelbeak commented
@Seokhun-Yang Fade 는 리뷰어에 할당이 되어 있지 않은데 이유가 있나요?

2022-05-21 02:51 UTC, LesserJang commented on src/main/java/net/teamuni/playerjoinandleave/UtilTool.java
> +                player.sendMessage(ChatColor.GREEN + "" + ChatColor.BOLD + "UtilTool has been reloaded!");
아뇨 안들어가도 됩니다

2022-05-21 04:42 UTC, Abel-rtzr commented on src/main/java/net/teamuni/playerjoinandleave/UtilTool.java
> +                player.sendMessage(ChatColor.GREEN + "" + ChatColor.BOLD + "UtilTool has been reloaded!");
그럼 필요치 않은 문자열은 제거해주는게 좋을거같네요 @Seokhun-Yang

2022-05-25 14:30 UTC, tjrhuni commented on src/main/java/net/teamuni/playerjoinandleave/UtilTool.java
> +                player.sendMessage(ChatColor.GREEN + "" + ChatColor.BOLD + "UtilTool has been reloaded!");
"" 를 제거하면 IDE에서 아래와 같은 경고가 나타나 GREEN과 BOLD 사이에 ""를 넣어주었습니다.

Operator '+' cannot be applied to 'org.bukkit.ChatColor', 'org.bukkit.ChatColor'

2022-05-25 14:30 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/playerjoinandleave/UtilTool.java
> +                CommandsManager.save();
리로드 명령어를 실행했을 때 예상되는 시나리오는 기존 config 파일에서 수정된 점이 있으면 수정된 정보를 불러오는 것입니다. 데이터의 바뀜은 config 파일이 수정된 경우라면 기존 정보에서 수정된 정보로 교체됩니다

2022-05-25 14:30 UTC, Seokhun-Yang commented on src/main/java/net/teamuni/playerjoinandleave/UtilTool.java
> +                Bukkit.getPluginManager().enablePlugin(this);
onEnable 메소드를 작동시키기 위함이였으나 다시 생각해보니 필요하지 않은 코드인 것 같습니다. 수정하도록 하겠습니다.

2022-05-25 14:35 UTC, Seokhun-Yang commented
제 기억으로는 페이드님도 리뷰어로 추가를 했었던 것 같은데 추가가 안 되어 있었네요.. 다음부터는 제대로 확인하겠습니다

2022-05-28 16:28 UTC, Fade-Jung approved these changes

2022-05-29 09:24 UTC, LesserJang approved these changes

2022-05-30 09:03 UTC, merged